name: backdoor_cl_eva
channels:
  - anaconda
  - metric-learning
  - pyg
  - gurobi
  - pytorch
  - Nvidia
  - nvidia
  - serge-sans-paille
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - anytree=2.8.0
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attrs=23.1.0
  - backcall=0.2.0
  - blas=1.0
  - blessed=1.19.1
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.0.4
  - cloog=0.18.1
  - colorama=0.4.6
  - colorful=0.5.4
  - comm=0.1.2
  - configargparse=1.4
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.2.140
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.2.144
  - cuda-nsight-compute=12.2.2
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.2.140
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.2.142
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.2.142
  - cuda-runtime=11.7.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.2.140
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - distlib=0.3.7
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.12.3
  - fire=0.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gcc_49=4.9.1
  - gds-tools=1.7.2.10
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-api-core=2.2.2
  - google-auth=2.22.0
  - google-auth-oauthlib=0.4.4
  - googleapis-common-protos=1.56.4
  - gpustat=1.1.1
  - grpc-cpp=1.39.0
  - grpcio=1.46.3
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gurobi=10.0.3
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_resources=6.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - isl=0.12.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20230802.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.1.112
  - libcufile=1.7.2.10
  - libcufile-dev=1.7.2.10
  - libcups=2.4.2
  - libcurand=10.3.3.141
  - libcurand-dev=10.3.3.141
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnpp=11.7.4.75
  - libnpp-dev=11.6.3.124
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libuuid=1.41.5
  - libuv=1.46.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - nodejs=10.13.0
  - nsight-compute=2023.2.2.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.26.0
  - numpy-base=1.26.0
  - nvidia-ml-py=12.535.108
  - oauthlib=3.2.2
  - opencensus=0.11.2
  - opencensus-context=0.1.3
  - openh264=2.1.1
  - openssl=3.1.3
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.36
  - protobuf=3.17.2
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-spy=0.3.14
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=1.10.12
  - pyg=2.3.1
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-metric-learning=1.6.3
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - ray-core=2.3.0
  - ray-dashboard=2.3.0
  - ray-default=2.3.0
  - re2=2022.06.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rpds-py=0.10.3
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - setproctitle=1.2.2
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - smart_open=6.4.0
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.2
  - termcolor=2.3.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - virtualenv=20.21.0
  - wcwidth=0.2.5
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zip=3.0
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cplex==22.1.1.0
      - pyqt5-sip==12.11.0
